# Метод array

In [2]:
import numpy as np

a = np.array([1,2,3], dtype= 'int')
print(np.__version__) 
print(a)
print(type(a))

1.26.4
[1 2 3]
<class 'numpy.ndarray'>


Объект массива в NumPy называется <u>ndarray</u> <b>(Приставка nd - это n мерный массив)</b>

Функция <b>array()</b>: 

<b>:return:</b> ndarray

<b>:param:</b> список, кортеж или другой объект похожий на матрицу

<b>:param: ndmin</b> При создании массива можно указать в параметрах минимальное dimensions


У объукта есть свойства:

<b>dtype</b> - возвращает тип данных массива

<b>base</b> - возвращает None, если объект не ссылается на другой массив, если ссылается, то возвращает массив на который он ссылается

<b>shape</b> - возвращает размер каждого измерения в виде кортежа 

In [5]:
print(np.array(52))# 0-D arrays or scalars
print(np.array([1, 2, 3])) # 1-D arrays(одномерный массив)
d2 = [[1,2],[2,3]]
print(np.array(d2)) # 2-D arrays
d3 = [[[1,2], [2,3]], [[3,4], [4,5]]]
print("3-D:")
print(np.array(d3)) # 3-D arrays
"""
Работает с массивом [1 2]
                    [2 3]
и возвращает (2, 2) - в виде кортежа, где первый элемент это кол-во строк(списков), второй - это кол-во столбцов(элементов внутри списка)
"""
print(np.array(d2).shape) 

"""
Пример работы shape c ndmin
"""

52
[1 2 3]
[[1 2]
 [2 3]]
3-D:
[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]
(1, 1, 2, 2)


'\nПример работы shape c ndmin\n'

атрибут <u>ndim</u> объекта ndarray

n -number
dim- dimension(измерение)

:return: его размерность (кол-во осей)

In [8]:
print(np.array(d3).ndim)

3


# Индексация 

Все также как и с обычным списком и массивом:

[number] - обращение к определенному элементу, начинается с 0
отрицательный индекс - для доступа с конца

In [9]:
current_array = np.array(d3)
print(current_array)
print("Примеры:")
print(f'1: {current_array[0, 0, 1]}')
print(f'2: {current_array[0][-1]}')
print(f'3:\n {current_array[-1]}')


[[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]
Примеры:
1: 2
2: [2 3]
3:
 [[3 4]
 [4 5]]


# Slicing arrays (Срезы)

Мы передаем срез вместо индекса следующим образом: [start= 0:end= -1 <u>[:step= 1]</u>]

Также могут передаваться и отрицательные значения

In [10]:
d2 = [[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6]]
current_array = np.array(d2)
print(f"Текущий массив:\n {current_array}")
print("Пример: ")

# Здесь я выбераю строку и делаю срез по столбцам, т.е. вот так: [2, 3, 4, 5] [-2:]
print(f"1: {current_array[1, -2:]}")

# Здесь я делаю срез(т.е. выбераю строки в диапазоне от 0 до 2 [0: 2]) и обращаюсь к столбцам по индексу 
# т.е.  
# [1, 2, 3, 4][1] --> 2 
# [2, 3, 4, 5][1] --> 3
print(f"2: {current_array[0:2, 1]}")

# делаю 
# [1, 2, 3, 4][-2:] --> [3 4] 
# [2, 3, 4, 5][-2:] --> [4 5]
print(f'3: \n{current_array[0:2, -2: ]}')

Текущий массив:
 [[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
Пример: 
1: [4 5]
2: [2 3]
3: 
[[3 4]
 [4 5]]


# Data Types in Numpy

Ниже приведён список всех типов данных в NumPy и символов, используемых для их обозначения.

<b>
i - целое число

b - логическое значение (почему-то не сработало: передавай через bool(не в видн строки)) 

u - целое число без знака

f - float

c - сложный float

m - timedelta

M - дата- время

O - объект

S - строка

U - строка в юникоде

V - исправлен фрагмент памяти для другого типа ( void )
</b>

Для того, чтобы определить размер: 

<b>Тип_данныхЧИСЛО</b> - означает массив с типом данных ЧИСЛО байта Тип_данных


<u>ValueError</u>
- возникает при неправильной передаче типа данных в параметр dtype

In [11]:
print(current_array.dtype) 
print(np.array(['arr', 'error']).dtype)
print(np.array([1, 2, 3], dtype= 'i4'))

int64
<U5
[1 2 3]


# Преобразование типов

Лучше всего преобразовывать тыпи с помощью метода объекта: 

<u>astype()</u> 

:param: Тип_данных_в_виде_строки 

:return: Копию объкта преобразованный в другой тип

In [12]:
new_array = current_array.astype('U')
print(current_array)
print(new_array)
new_array = current_array.astype('f')
print(new_array)
print(new_array.dtype)
new_array = current_array.astype(bool)
print(new_array)

[[1 2 3 4]
 [2 3 4 5]
 [3 4 5 6]]
[['1' '2' '3' '4']
 ['2' '3' '4' '5']
 ['3' '4' '5' '6']]
[[1. 2. 3. 4.]
 [2. 3. 4. 5.]
 [3. 4. 5. 6.]]
float32
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True  True  True]]


# Copy и View arrays


copy() - создает копию массива 
veiw() - создает обычную ссылку на массив(изменения в представлении(view) влияют на основной массив и наоборот)

In [19]:
current_array = np.array(d3)
copy_array = current_array.copy()
view_array = current_array.view()
copy_array[0, 0, 0] = 5
print(f'COPY:\n{copy_array}\n {current_array}')
view_array[0, 0, 0] = 99
print(f'VIEW\n{view_array}\n {current_array}')

COPY:
[[[5 2]
  [2 3]]

 [[3 4]
  [4 5]]]
 [[[1 2]
  [2 3]]

 [[3 4]
  [4 5]]]
VIEW
[[[99  2]
  [ 2  3]]

 [[ 3  4]
  [ 4  5]]]
 [[[99  2]
  [ 2  3]]

 [[ 3  4]
  [ 4  5]]]


# Изменение формы массива 
shape - форма

Осуществляется с помощью метода 

<b>reshape( )</b>

<b>:param: shape - размерность массива</b> 
Если shape = -1, то происходит Flattening array(Сглаживание массива) 
только один из цифр в кортеже может быть равен -1 - тогда кол-во цифр определяется автоматически...

<b>:return: ndarray - измененный массив</b>

<u>
Внимание!!!

Кол-во элементов у таблицы должен совпадать с количеством элементов после изменения формы 

Иначе ошибка <b>ValueError</b>
</u>

In [25]:
import numpy as np

current_array = np.array([1, 2, 3, 4, 5, 6])
new_array = current_array.reshape(2, 3)
print("Пример:")
print(current_array)

current_array[0] = 9
print("Изменим форму массива")
print(new_array)

print(f"Возвращает {new_array.base} следовательно является VIEW")
print(f'Сглаживание массива {new_array.reshape(-1)}')

print(np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]).reshape(2, -1, 2))
print(current_array.reshape(3, 3))


Пример:
[1 2 3 4 5 6]
Изменим форму массива
[[9 2 3]
 [4 5 6]]
Возвращает [9 2 3 4 5 6] следовательно является VIEW
Сглаживание массива [9 2 3 4 5 6]
[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


ValueError: cannot reshape array of size 6 into shape (3,3)