https://pythonist.ru/python-numpy-tutorial/

In [2]:
import numpy as np 
arr = np.array([1, 2, 3, 4, 5]) # список
print(arr) 
arr = np.array((1, 2, 3, 4, 5)) # Кортеж
print(arr)

# Вывод:
# [1 2 3 4 5]

[1 2 3 4 5]
[1 2 3 4 5]


In [8]:
arr = np.array(36) 
print(arr) #0d
print("!" * 10)
arr = np.array([1, 2, 3, 4, 5]) 
print(arr) #1d
print("!" * 10)
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]]) 
print(arr1)#2d
print("!" * 10)
arr1 = np.array([[[1, 2, 3],
                  [4, 5, 6]],

                 [[1, 2, 3],
                  [4, 5, 6]]]) 
print(arr1) #3d

print("Размеры массивывов:",arr.ndim)
print(arr1.ndim)

36
!!!!!!!!!!
[1 2 3 4 5]
!!!!!!!!!!
[[1 2 3]
 [4 5 6]]
!!!!!!!!!!
[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]
Размеры массивывов: 1
3


# ndarray

Наиболее важным объектом, определенным в NumPy, является N-мерный тип массива, называемый ndarray. Он описывает коллекцию элементов одного типа. Доступ к элементам коллекции осуществляется с помощью индекса.

Каждый элемент массива ndarray занимает тот же размер, что и блок в памяти. Каждый элемент ndarray представляет собой объект типа data (называемый dtype).

Экземпляр класса ndarray может быть создан с помощью различных методов создания массивов (их мы еще рассмотрим). Базовый ndarray создается с использованием функции array в NumPy следующим образом: numpy.array().

Это создает ndarray из любого объекта с реализацией интерфейса массива или из любого метода, возвращающего массив.

Объект ndarray представляет собой непрерывный одномерный сегмент памяти компьютера, объединенный со схемой индексации, которая сопоставляет каждому элементу место в блоке памяти.

In [9]:
np.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)

array(<class 'object'>, dtype=object)

# Параметры

<u>Параметр</u>	    Описание

<u>object</u>	    Любой объект, экспонирующий метод интерфейса массива, возвращает массив или любую (вложенную) последовательность.

<u>dtype</u>	    Желаемый тип данных массива.

<u>copy</u>	    Опциональное копирование. По умолчанию (true), объект копируется. При создании нового массива из существующего, по умолчанию (значение True для параметра copy) создается полная копия исходного массива. Это значит, что изменения в новом массиве не повлияют на оригинал.

<u>order</u>	    C (по строкам) или F (по столбцам) или A (любой) (по умолчанию).

<u>subok</u>	    По умолчанию возвращаемый массив принудительно преобразуется в базовый класс массива.Если true, допускаются подклассы.

<u>ndmin</u>	    Задает минимальное количество измерений результирующего массива.

In [14]:
# minimum dimensions 
import numpy as np 

a = np.array([1, 2, 3,4,5], ndmin = 2) 
print(a.ndim)
print(a)

# dtype parameter 
a = np.array([1, 2, 3], dtype = complex)
print(a)





2
[[1 2 3 4 5]]
[1.+0.j 2.+0.j 3.+0.j]


# Преобразование типа данных

numpy.dtype(object, align, copy)

Порядок следования байтов определяется префиксом ‘<‘ или ‘>’ к типу данных. ‘<‘ означает, что кодировка является little-endian (младший разряд хранится по наименьшему адресу). ‘>’ означает, что кодировка big-endian (старший байт хранится по наименьшему адресу).

<u>object</u> — преобразуемый в объект тип данных

<u>align</u> — если значение равно True, то добавляется выравнивание (padding) для поля, чтобы сделать его аналогичным C-структуре.

<u>copy</u> — создает новую копию объекта dtype. Если False, то результатом будет ссылка на встроенный объект типа данных

или через astype(dtype)

In [17]:
#int8, int16, int32, int64 can be replaced by equivalent string 'i1', 'i2','i4', etc. 
import numpy as np 
dt = np.dtype('i4')
print(dt)

# using endian notation 
dt = np.dtype('>i4') 
print(dt)

# Вывод:
# >i4

int32
>i4


В следующих примерах показано использование структурированного типа данных. Здесь необходимо объявить имя поля и соответствующий скалярный тип данных.

In [20]:
# first create structured data type 
import numpy as np 
dt = np.dtype([('age',np.int8)]) 
print(dt)
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print(a)
# Вывод:
# [('age', 'i1')]

[('age', 'i1')]
[(10,) (20,) (30,)]


Каждый встроенный тип данных имеет символьный код, который уникально идентифицирует его.

‘b’ — булевый (логический) тип данных

‘i’ — (знаковый) целочисленный тип данных

‘u’ — беззнаковый целочисленный тип данных

‘f’ — тип данных с плавающей запятой (вещественные числа)

‘c’ — комплексный тип данных с плавающей запятой

‘m’ — тип данных timedelta (разница между двумя моментами времени)

‘M’ — тип данных datetime (дата и время)

‘O’ — тип данных для объектов Python

‘S’, ‘a’ — тип данных для байтовой строки (ASCII-строки)

‘U’ — тип данных для строк Unicode

‘V’ — тип данных для необработанных данных (пустой тип)

In [23]:
import numpy as np 
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) 
print(a)
a = a.reshape(2,-1)
print(a)

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


In [25]:
import numpy as np 
a = np.arange(24) 
print(a)
print(a.ndim)  
# now reshape it 
b = a.reshape(2,4,3) 
print (b) 

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
1
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


<u>numpy.itemsize</u>

Этот атрибут массива возвращает длину каждого элемента массива в байтах.

In [28]:
import numpy as np 
x = np.array([1,2,3,4,5], dtype = np.int8)
print (x, x.itemsize)

x = np.array([1,2,3,4,5], dtype = np.float32) 
print(x, x.itemsize)

[1 2 3 4 5] 1
[1. 2. 3. 4. 5.] 4


<u>numpy.flags</u>
Объект ndarray имеет следующие атрибуты:

<u>Атрибут</u>	Описание

<u>C_CONTIGUOUS</u> (C)	Данные находятся в одном сегменте в стиле C (последовательно в памяти)

<u>F_CONTIGUOUS</u> (F)	Данные находятся в одном сегменте в стиле Fortran (последовательно в памяти)

<u>OWNDATA</u> (O)	Массив владеет своей памятью или заимствует ее у другого объекта

<u>WRITEABLE</u> (W)	Область данных можно записывать. Установка этого значения в False блокирует данные, делая их доступными только для чтения

<u>ALIGNED</u> (A)	Данные и все элементы выровнены соответствующим образом для аппаратного обеспечения

<u>UPDATEIFCOPY</u> (U)	Этот массив является копией другого массива. При удалении этого массива базовый массив будет обновлен содержимым этого массива


Текущие значения атрибутов возвращаются функцией flags. В следующем примере показаны текущие значения флагов.

In [29]:
import numpy as np 
x = np.array([1,2,3,4,5]) 
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



<U>numpy.empty()</u>

Создает неинициализированный массив заданной формы и dtype. Вот пример с параметрами:

<U>numpy.empty(shape, dtype = float, order = 'C')</u>.

<U>shape</u> — форма пустого массива в виде целого числа или кортежа целых чисел

<U>dtype</u> — желаемый тип данных для выходного массива. Необязательный параметр

<U>order</u> — может иметь значение ‘C’ для массива в стиле C (по строкам) или ‘F’ для массива в стиле Fortran (по столбцам)

In [32]:
import numpy as np
x = np.empty((3, 2), dtype= int)
print(x)

[[1 2]
 [3 4]
 [5 6]]
