In [39]:
import numpy as np
x = np.array([1, 2, 3, 4])
y = np.array([9, 2, 3, 4])
k = 5
print(x + y) # поэлементное сложение
print(k * x)
print(x.tolist())
print(x.T) # для одномерной матрицы ничего не меняется 
print(np.array([[1],
               [2],
               [3]])) # имеет разницу

x = np.array([x.tolist(),y.tolist()]) # надо ставить [], т.к. внутри массива у нас два подмассива

print(x.transpose())
print(x.T)


[10  4  6  8]
[ 5 10 15 20]
[1, 2, 3, 4]
[1 2 3 4]
[[1]
 [2]
 [3]]
[[1 9]
 [2 2]
 [3 3]
 [4 4]]
[[1 9]
 [2 2]
 [3 3]
 [4 4]]


In [61]:
from numpy import linalg as l 
x = np.array([1, 2, 3])
print(x)
y = np.array([2, 3, 4])
print(y)

print(l.norm(x)) # находит длину одного вектора

print(np.sqrt(((x - y) ** 2).sum()))# находит растояние между двумя точками (векторами идущих из начала координат)
print(l.norm((x - y))) # аналогично


print(np.power(x, 2))
print(np.power(x, 2).sum())
print(np.sqrt(np.power(x, 2).sum()))

[1 2 3]
[2 3 4]
3.7416573867739413
1.7320508075688772
1.7320508075688772
[1 4 9]
14
3.7416573867739413


In [56]:
x = np.array([1, 2, 3])
y = np.array([2, 3, 4])
print(x * y) # поэлементное произведение

print(np.outer(x, y)) # произведени 2-х матриц

# !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

print(x @ y) # скалярное произведение
print(np.dot(x, y)) # сколярное произведение
print(np.inner(x, y))

[ 2  6 12]
[[ 2  3  4]
 [ 4  6  8]
 [ 6  9 12]]
20
20
20


In [55]:
# посчитаем косинус между векторами
cosa = x @ y / (l.norm(x) * l.norm(y))

print(cosa)
theta_rad = np.arccos(cosa) # возвращает угл в радианах
print(theta_rad)
a = theta_rad * 180 / np.pi
print(a)

0.9925833339709303
0.12186756768575456
6.98249728791863


# Умножение матриц

Свойства:

- коммутативность: в общем случае 
$AB \neq BA$
- ассоциативность: 
$A\left(BC\right) =  \left(AB\right)C $</li>
- дистрибутивность по сложению: 
$A\left(B+C\right) =  AB+AC $ и $\left(A+B\right)C =  AC+BC $