Создание двумерного массива

Создайте двумерный массив (матрицу) размером 4x4, заполненный случайными целыми числами от 1 до 100.

In [1]:
import numpy as np 

ndarray = np.array([], ndmin= 2)
A = np.random.randint(1, 100, size= (4, 2))
B = np.random.randint(1, 100, size= (4, 2)) 
print(A, B)
ndarray = np.append(A, B, axis= 1)
ndarray

[[46 39]
 [96 31]
 [64 45]
 [59 44]] [[29 52]
 [50 54]
 [14 90]
 [75 69]]


array([[46, 39, 29, 52],
       [96, 31, 50, 54],
       [64, 45, 14, 90],
       [59, 44, 75, 69]])

Извлеките первый и третий ряды (строки) из матрицы.

Извлеките второй и четвертый столбцы.

In [2]:
print(ndarray[:,[0,2]])
print(ndarray[(1,3),:])

[[46 29]
 [96 50]
 [64 14]
 [59 75]]
[[96 31 50 54]
 [59 44 75 69]]


Привести массив к другому типу

In [3]:
ndarray.astype('float64')

array([[46., 39., 29., 52.],
       [96., 31., 50., 54.],
       [64., 45., 14., 90.],
       [59., 44., 75., 69.]])

Увеличьте все элементы матрицы на 10.

Замените элемент в третьей строке и втором столбце на значение 0.

In [4]:
print(ndarray + 10)
ndarray[2,1] = 0 
print(ndarray)

[[ 56  49  39  62]
 [106  41  60  64]
 [ 74  55  24 100]
 [ 69  54  85  79]]
[[46 39 29 52]
 [96 31 50 54]
 [64  0 14 90]
 [59 44 75 69]]


In [5]:
import numpy as np

A = np.random.randint(1, 11, size= (1, 10))
B = np.random.randint(1, 11, size= (1, 10))
C = np.random.randint(1, 11, size= (1, 10))

print(f"A:\n {A}")

print(f"B:\n {B}")

print(f"C:\n {C}")

print("Concate:\n", np.concatenate((A, B), axis= 0))

print("Vstack:\n", np.vstack([B,C]))

print('Hstack:\n', np.hstack([A, C]))

print("Np_c:",  np.c_[B[:, :3], C])

print("np_r:", np.r_[A, C])

A:
 [[ 9  1  9  1  7  5  6  1 10  4]]
B:
 [[2 7 2 7 7 3 4 4 8 6]]
C:
 [[5 2 4 8 7 3 6 5 3 7]]
Concate:
 [[ 9  1  9  1  7  5  6  1 10  4]
 [ 2  7  2  7  7  3  4  4  8  6]]
Vstack:
 [[2 7 2 7 7 3 4 4 8 6]
 [5 2 4 8 7 3 6 5 3 7]]
Hstack:
 [[ 9  1  9  1  7  5  6  1 10  4  5  2  4  8  7  3  6  5  3  7]]
Np_c: [[2 7 2 5 2 4 8 7 3 6 5 3 7]]
np_r: [[ 9  1  9  1  7  5  6  1 10  4]
 [ 5  2  4  8  7  3  6  5  3  7]]


In [6]:
import numpy as np
A = np.array([1, 2, 
              3, 4]).reshape(2, -1)
B = np.array([5, 6,
              7, 8]).reshape(2, -1)
C = np.array([9, 10, 
              11, 12]).reshape(2, -1)

D = np.stack((A, B, C), axis= 2)
F = np.concatenate([A, B, C], axis= 1)
print(D)
print(F)

[[[ 1  5  9]
  [ 2  6 10]]

 [[ 3  7 11]
  [ 4  8 12]]]
[[ 1  2  5  6  9 10]
 [ 3  4  7  8 11 12]]


In [7]:
import numpy as np
A = np.array([[1, 2, 3, 4],
              [4, 5, 6, 0],
              [7, 8, 9, 0]])
print(np.delete(arr= A, obj= (0, 2), axis= 1))
print(A.shape, A.ndim)

[[2 4]
 [5 0]
 [8 0]]
(3, 4) 2


In [8]:
print(A.transpose())
print(A.reshape((2, 2, -1)), A.reshape((2, 2, -1)).flatten())


[[1 4 7]
 [2 5 8]
 [3 6 9]
 [4 0 0]]
[[[1 2 3]
  [4 4 5]]

 [[6 0 7]
  [8 9 0]]] [1 2 3 4 4 5 6 0 7 8 9 0]


In [9]:
import numpy as np
np.random.seed(1)
A = np.random.randint(1, 10, size=(2, 3))
print("Исходный массив:\n",A)
B = np.zeros((3, 4), int)
print(B)
C = np.ones((2, 3), int)
print(C)
D = np.full((3, 3), 6)
print(D)

Исходный массив:
 [[6 9 6]
 [1 1 2]]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1]
 [1 1 1]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]


In [10]:
# Диапазон значений
F = np.arange(stop= 5, step= 0.5) # шаг мы выставляем 
print(F)
# 
G = np.linspace(start=0, stop= 5, num=  20) # шаг сам высчитыввает
print(G)
E = np.linspace(start=0, stop= 5, num=  10, endpoint= True, retstep= True) # шаг сам высчитыввает
print(E)
B = np.logspace(
    start= 7, # Стартовая степень
    stop= 10, # Конечная степень
    num= 5, 
    endpoint= False,
    base= 2) # в основании 2 
print(B)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0.         0.26315789 0.52631579 0.78947368 1.05263158 1.31578947
 1.57894737 1.84210526 2.10526316 2.36842105 2.63157895 2.89473684
 3.15789474 3.42105263 3.68421053 3.94736842 4.21052632 4.47368421
 4.73684211 5.        ]
(array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ]), 0.5555555555555556)
[128.         194.01172051 294.06677888 445.72188841 675.58805032]


In [11]:
print((B > 128))
print((B > 128) & (B < 300)) # Каждый элемент превращается в тип bool
# Вместо and --> &
print(B)

[False  True  True  True  True]
[False  True  True False False]
[128.         194.01172051 294.06677888 445.72188841 675.58805032]


In [12]:
np.random.seed(1)
X = np.random.randint(1, 10, size= (3, 3))
print(X)
print(X[(X < 5) & (X > 1)]) # выбор элементов по условию
print(X[ # выбор по индексу
    [0, 1, 2],  # координаты по X
    [0, 1, 2] # координаты по Y
])

[[6 9 6]
 [1 1 2]
 [8 7 3]]
[2 3]
[6 1 3]


# Флаги

In [13]:
C = np.random.randint(0, 2, size= (3, 3), dtype= 'bool') # Для типа bool start = 0, stop = 2
print(X)
print(C)
print(X[C]) # УБИРАЕТ элементы с позиции False

[[6 9 6]
 [1 1 2]
 [8 7 3]]
[[False False  True]
 [False  True False]
 [False False  True]]
[6 1 3]


In [14]:
print(X.sum(axis= 1)) # сложение по "строчкам" axis = 1
print(X.sum(axis= 0))  # сложение по "столбцам" axis = 0

print(X[X.sum(axis= 1) > 10]) # вывод строк, где сумма элементов больше 10
print(X[[0, 2]])
X[:,[0, 2]]

[21  4 18]
[15 17 11]
[[6 9 6]
 [8 7 3]]
[[6 9 6]
 [8 7 3]]


array([[6, 6],
       [1, 2],
       [8, 3]])

In [20]:
print(X)
print(np.where(X < 5)) # возвращает координаты по X и по Y элементов вернувших True

print(X[X<5]) # Возвращает сами элементы

print(np.where(X < 5, X, -1))

[[6 9 6]
 [1 1 2]
 [8 7 3]]
(array([1, 1, 1, 2]), array([0, 1, 2, 2]))
[1 1 2 3]
[[-1 -1 -1]
 [ 1  1  2]
 [-1 -1  3]]


In [23]:
%%timeit
def add_2(x):
    return x + 2

new_x = np.vectorize(add_2) # делает функцию применимой для ndarray
new_x(X)

4.67 μs ± 98 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [24]:
%%timeit
from numba import vectorize
@vectorize
def add_2(x):
    return x + 2

new_x = add_2(X)
print(new_x)

[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[[ 8 11  8]
 [ 3  3  4]
 [10  9  5]]
[